platform :ios, '9.0'
use_frameworks!

def core_pods
	pod 'Fabric'
	pod 'Crashlytics'
	pod 'ObjectMapper'
end

target 'TheGauntlet' do
	core_pods
end

target 'TheGauntletTests' do

end

target 'TheGauntletUITests' do

end

