# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

def core_pods
	pod 'Fabric'
	pod 'Crashlytics'
end

target 'TheGauntlet' do
	core_pods
end

target 'TheGauntletTests' do

end

target 'TheGauntletUITests' do

end

